### ISSUE TITLE
Failed to authenticate using Postgres.

### ISSUE THREAD

**Issue by aderbas** [iegomez/mosquitto-go-auth#347]
I'm trying to configure it to authenticate using Postgres. I'm following the documentation, as it's the first time configuring the plugin I may be doing something wrong, or forgetting something.

I am using the docker image: iegomez/mosquitto-go-auth

Docker compose service:

```
  mosquitto:
    image: iegomez/mosquitto-go-auth
    hostname: mosquitto
    container_name: ${APP_NAME}_mqtt
    restart: unless-stopped
    ports:
      - "${MQTT_EXTERNAL_PORT}:1883"
      - "9001:9001"
      - "1884:1884"
      - "8000:8000"
    expose:
      - "${MQTT_EXTERNAL_PORT}"
      - "9001"
      - "1884"
      - "8000"
    volumes:
      - ./docker-compose/mqtt/passwd_file:/etc/mosquitto/passwd_file
      - ./docker-compose/mqtt/mosquitto.conf:/etc/mosquitto/mosquitto.conf
      - ./docker-compose/mqtt/go-auth.conf:/etc/mosquitto/conf.d/go-auth.conf
    depends_on:
      - database
```

This is my mosquitto.conf

```
listener 1883

password_file /etc/mosquitto/passwd_file
allow_anonymous false

persistence true
persistence_location /var/lib/mosquitto/

log_dest stderr
log_dest file /var/log/mosquitto/mosquitto.log

include_dir /etc/mosquitto/conf.d
```

This is my go-auth.conf

```
# Plain MQTT protocol
listener 1884

socket_domain ipv4
max_connections 1024
use_username_as_clientid true
allow_zero_length_clientid false


# Plain WebSockets configuration
listener 8000
protocol websockets


auth_plugin /mosquitto/go-auth.so
auth_opt_log_dest file
auth_opt_log_level debug
auth_opt_log_file /var/log/mosquitto/mosquitto_auth.log

auth_opt_backends postgres

auth_opt_check_prefix false
allow_anonymous false

auth_opt_hasher pbkdf2

auth_opt_hasher_salt_size 16
auth_opt_hasher_iterations 100000
auth_opt_hasher_keylen 64
auth_opt_hasher_algorithm sha512
auth_opt_hasher_salt_encoding base64

# Postgres configuration
auth_opt_pg_host database
auth_opt_pg_port 5432
auth_opt_pg_dbname <my db name>
auth_opt_pg_user <my db user>
auth_opt_pg_password <my db password>

auth_opt_pg_connect_tries 5
auth_opt_pg_sslmode disable

auth_opt_pg_userquery SELECT mqtt_hash_password FROM mqtt_user WHERE username = $1 limit 1

```
Mosquitto log:
```
1744198903: mosquitto version 2.0.15 starting
1744198903: Config loaded from /etc/mosquitto/mosquitto.conf.
1744198903: Loading plugin: /mosquitto/go-auth.so
1744198903:  ├── Username/password checking enabled.
1744198903:  ├── TLS-PSK checking enabled.
1744198903:  └── Extended authentication not enabled.
1744198903: Opening ipv4 listen socket on port 1883.
1744198903: Opening ipv4 listen socket on port 1884.
1744198903: Opening ipv6 listen socket on port 1884.
1744198903: Opening websockets listen socket on port 8000.
1744198903: mosquitto version 2.0.15 running
1744198925: New connection from 172.18.0.1:56120 on port 1884.
1744198925: Client 8765894639236737 disconnected, not authorised.
```
Auth log:
```
time="2025-04-09T11:41:43Z" level=info msg="backend registered: Postgres"
time="2025-04-09T11:41:43Z" level=info msg="registered acl checker: postgres"
time="2025-04-09T11:41:43Z" level=info msg="registered user checker: postgres"
time="2025-04-09T11:41:43Z" level=info msg="registered superuser checker: postgres"
time="2025-04-09T11:41:43Z" level=info msg="No cache set."
```
I noticed that I am getting: ```Extended authentication not enabled```. I don't know if this is the problem of not authenticating.

Can anyone help me? If you need more information. I appreciate it.
