### ISSUE TITLE
How to generate PBKDF2 password ?

### ISSUE THREAD

**Issue by vvksahoo** [iegomez/mosquitto-go-auth#47]
Hi,
I want deploy mosquitto-go-auth in docker.
```
version: "3"

services:
  mosquitto:
    image: iegomez/mosquitto-go-auth:0.5.0
    volumes:
      - ./conf:/etc/mosquitto
    ports:
      - 1883:1883
```
Once container is spin up , doing docker exec -it <container_name>  /bin/bash and try to execute this '/opt/mosquitto-auth-plug/n' to generate the password so getting error saying 'there no such file/directory ' . Cant identity what i am doing wrong here ?
